### ISSUE TITLE
Gradle, adt, android plugin upgrade rollout

### ISSUE THREAD

**Issue by stonier** [rosjava/rosjava#1]
Gradle 1.6-1.7, Adt 17->18.1.1, Android Plugin 0.5.6->0.6.1

Now damon's updated these in rosjava_build_tools and rosjava_bootstrap we should roll them out through all rosjava repos here. Any objections?
- [x] Update gradle version and adt in [rosjava_bootstrap/gradle_plugins](https://github.com/rosjava/rosjava_bootstrap/pull/5)
- [x] Version bump [rosjava_bootstrap](https://github.com/rosjava/rosjava_bootstrap/pull/8)
- [x] Update adt and gradle versions in the templates in [rosjava_build_tools](https://github.com/rosjava/rosjava_build_tools/pull/5)
- [x] Update gradle version in [rosjava_core](https://github.com/rosjava/rosjava_core/pull/179)
- [x] Update gradle version in [rosjava_extras](https://github.com/rosjava/rosjava_extras/pull/6)
- [x] Update gradle version in [zeroconf_jmdns_suite](https://github.com/rosjava/zeroconf_jmdns_suite/pull/38)
- [x] Update gradle version in [android_core](https://github.com/rosjava/android_core/pull/176)
- [x] Update gradle version in [android_extras](https://github.com/rosjava/android_extras/commit/fa26dc512182ec63af0d004c3baf64830fa8ff02)
- [x] Update gradle version in [android_apps](https://github.com/rosjava/android_apps/commit/adabc2c0649f5aa7295ca2d6c00b54ba039aca86)
- [x] Update gradle version in [android_remocons](https://github.com/rosjava/android_remocons/commit/5d0c36e8f6679d13a9635b36e8832425d0159a3f).
- [x] Backport these changes to hydro (new downloaders will be using the new android studio..thus)
- [x] Re-release hydro debs
- [x] upload hydro maven artifacts.

**Comment by damonkohler** [comment]
SGTM

**Comment by stonier** [comment]
Just have to check on the debs, but effectively this is closed.
