### ISSUE TITLE
rosjava installation problem. (download URL not found)

### ISSUE THREAD

**Issue by jim1949** [rosjava/rosjava#14]
Hi, I want to install rosjava in my labtop. And I follow the instructions

http://wiki.ros.org/rosjava/Tutorials/indigo/Source%20Installation
And in step 3.3, When I input:

wstool merge https://raw.githubusercontent.com/me/rosinstalls/master/my_custom_msg_repos.rosinstall
I got the error:

ERROR in config: Unable to download URL [https://raw.githubusercontent.com/me/rosinstalls/master/my_custom_msg_repos.rosinstall ]: HTTP Error 404: Not Found
It seems the address is not existed any more. Anyone has the idea what problem is this? How can I solve this problem?

**Comment by adamantivm** [comment]
@jim1949 "my_custom_msg_repos" is only an example, not a real URL. It is intended to be replaced by whatever rosinstall you want to create yourself.
That part assumes that you are familiar with wstool and rosinstalls which are standard ROS tools. It is only showing you how you would use those already known tools for rosjava.

**Comment by jim1949** [comment]
Many thanks, I figure out this problem.
