### ISSUE TITLE
Maven style open ranged dependencies

### ISSUE THREAD

**Issue by stonier** [rosjava/rosjava#3]
This is a result of the discussion https://github.com/rosjava/rosjava_mvn_repo/issues/15.

Basically we need to move from `0.1.+` -> `[0.1,)` which is the official format for maven pom's. This lets non gradle people use the repository as well as gradle people.

Gradle supports this, see [here](http://forums.gradle.org/gradle/topics/mavin_plugin_pom_generator_doesnt_handle_map_gradle_dynamic_dependency_correctly_to_maven_dynamic_dependency) and I've in fact tested and moved across the hydro branches already so we can set up the repository correctly.

We need to do this for the master branches too. One question though....

There is a deprecated message when upgrading like this:

```
Error listing versions of org.ros.rosjava_messages:diagnostic_msgs:[1.10,) using class org.gradle.api.internal.artifacts.repositories.resolver.MavenVersionLister$1. Will attempt an alternate way to list versions. This behaviour has been deprecated and is scheduled to be removed in Gradle 2.0
```

While on gradle 1.8 this doesn't break the compile, but I'll be damned if I can figure out where the proper format for gradle 2.0's MavenVersionLister is.

**Comment by stonier** [comment]
Pull requests, these include the version bumps (#4) as well.
- [x] [rosjava_build_tools](https://github.com/rosjava/rosjava_build_tools/pull/11)
- [x] [rosjava_bootstrap](https://github.com/rosjava/rosjava_bootstrap/pull/9)
- [x] <del>[rosjava_messages](https://github.com/rosjava/rosjava_messages/pull/7)</del> : cancelling updates on master branch (see below)
- [x] [rosjava_core](https://github.com/rosjava/rosjava_core/pull/182)
- [x] [rosjava_extras](https://github.com/rosjava/rosjava_extras/pull/7)
- [x] [zeroconf_jmdns_suite](https://github.com/rosjava/zeroconf_jmdns_suite/pull/39)
- [x] [android_core](https://github.com/rosjava/android_core/pull/180)
- [x] [android_extras](https://github.com/rosjava/android_extras/pull/4)
- [x] [android_apps](https://github.com/rosjava/android_apps/pull/29)
- [x] [android_remocons](https://github.com/rosjava/android_remocons/pull/38)

**Comment by stonier** [comment]
@damonkohler : can you look at a couple of these just to make sure you're ok with them? If all is good and you just want to check the important ones, I can follow up on the others.

I'll clean up the open_range branches before closing.

**Comment by stonier** [comment]
Hold off on merging the pull requests...I have to fix the conversion: 0.2.+ -> [0.2, 0.3).

**Comment by damonkohler** [comment]
Should I still hold off, @stonier?

**Comment by stonier** [comment]
Should be good to go now - there are some pushes in each of the pull requests that cover the following points:
- Ivy range dependency of 0.2.x corresponds to maven range dependency of [0.2,0.3) (I previously had [0.2,))
- Added use of environment variable ROS_MAVEN_REPOSITORY so we can point to an offline clone or forked repo.

Would also like to drop master branch of rosjava_messages (see this [issue](https://github.com/rosjava/rosjava_messages/issues/4)) so I didn't push further changes and closed that pull request.

**Comment by stonier** [comment]
@damonkohler - if you can give it a quick scan and have no objections I'll merge this on Monday. I need these to go in so some other fixes to messge generation can go in and don't want things piling up too much in one pull request.

**Comment by damonkohler** [comment]
I noticed that the version range has changed. To match the old behavior, they should be of the form [x.x.x,) but this PR has the form [x.x.x,y.y.y). I'm not sure if that was intentional, but I believe the [x.x.x,) form is what we should be using.

I'm also in the middle of a lot of gradle changes to fix bugs and add snapshot versions. I'm not sure when I'll get those sent out though, so feel free to merge this in before hand.

**Comment by stonier** [comment]
I was initially just trying to transfer the original ivy specification of 0.2.+ which exactly matches [0.2,0.3) in maven.

But you are probably right with regards to the master branch. It is important to the releases though, which is where I was putting most of my thoughts. e.g. the hydro versions really need an upper limit (there it is typically [0.1,0.2)) so that it protects it from from pulling any future incompatible master/igloo artifact dependencies that will be versioned beyond 0.2.

I used the minor version to define the limits, though if you were really strict about versioning, depending on anything up to a backwards-breaking major version change should be ok.

**Comment by stonier** [comment]
rosjava_messages master branch also deleted.
